// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	domain "github.com/Gadzet005/GoType/backend/internal/domain/User"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Authorization is an autogenerated mock type for the Authorization type
type Authorization struct {
	mock.Mock
}

// CreateSeniorAdmin provides a mock function with given fields: name, password
func (_m *Authorization) CreateSeniorAdmin(name string, password string) error {
	ret := _m.Called(name, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeniorAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: user
func (_m *Authorization) CreateUser(user domain.User) (int, int, string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int
	var r1 int
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(domain.User) (int, int, string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(domain.User) int); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain.User) int); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(domain.User) string); ok {
		r2 = rf(user)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(domain.User) error); ok {
		r3 = rf(user)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetUser provides a mock function with given fields: username, password
func (_m *Authorization) GetUser(username string, password string) (domain.User, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (domain.User, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) domain.User); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: id
func (_m *Authorization) GetUserById(id int) (domain.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) domain.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetUserRefreshToken provides a mock function with given fields: id, refreshToken, expiresAt
func (_m *Authorization) SetUserRefreshToken(id int, refreshToken string, expiresAt time.Time) (int, int, string, error) {
	ret := _m.Called(id, refreshToken, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRefreshToken")
	}

	var r0 int
	var r1 int
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(int, string, time.Time) (int, int, string, error)); ok {
		return rf(id, refreshToken, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(int, string, time.Time) int); ok {
		r0 = rf(id, refreshToken, expiresAt)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, string, time.Time) int); ok {
		r1 = rf(id, refreshToken, expiresAt)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, string, time.Time) string); ok {
		r2 = rf(id, refreshToken, expiresAt)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(int, string, time.Time) error); ok {
		r3 = rf(id, refreshToken, expiresAt)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewAuthorization creates a new instance of Authorization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorization(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authorization {
	mock := &Authorization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
