port: "8080"

db:
  username: "gotype"
  host: "db"
  port: "5432"
  dbname: "gotypedb"
  sslmode: "disable"

cache:
  host: "cache"
  port: "6379"
  db: "0"

logs:
  mode: "file" #console/file
  file: "logs/app.log" #path to file