// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	domain "github.com/Gadzet005/GoType/backend/internal/domain/Level"
	Statistics "github.com/Gadzet005/GoType/backend/internal/domain/Statistics"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// Level is an autogenerated mock type for the Level type
type Level struct {
	mock.Mock
}

// CheckLevelExists provides a mock function with given fields: levInfo
func (_m *Level) CheckLevelExists(levInfo domain.GetLevelInfoStruct) (string, error) {
	ret := _m.Called(levInfo)

	if len(ret) == 0 {
		panic("no return value specified for CheckLevelExists")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.GetLevelInfoStruct) (string, error)); ok {
		return rf(levInfo)
	}
	if rf, ok := ret.Get(0).(func(domain.GetLevelInfoStruct) string); ok {
		r0 = rf(levInfo)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.GetLevelInfoStruct) error); ok {
		r1 = rf(levInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLevel provides a mock function with given fields: userId, levelFile, infoFile, previewFile
func (_m *Level) CreateLevel(userId int, levelFile *multipart.FileHeader, infoFile *multipart.FileHeader, previewFile *multipart.FileHeader) (int, error) {
	ret := _m.Called(userId, levelFile, infoFile, previewFile)

	if len(ret) == 0 {
		panic("no return value specified for CreateLevel")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, *multipart.FileHeader, *multipart.FileHeader, *multipart.FileHeader) (int, error)); ok {
		return rf(userId, levelFile, infoFile, previewFile)
	}
	if rf, ok := ret.Get(0).(func(int, *multipart.FileHeader, *multipart.FileHeader, *multipart.FileHeader) int); ok {
		r0 = rf(userId, levelFile, infoFile, previewFile)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, *multipart.FileHeader, *multipart.FileHeader, *multipart.FileHeader) error); ok {
		r1 = rf(userId, levelFile, infoFile, previewFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLevel provides a mock function with given fields: levelId
func (_m *Level) DeleteLevel(levelId int) error {
	ret := _m.Called(levelId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(levelId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLevelById provides a mock function with given fields: levelId
func (_m *Level) GetLevelById(levelId int) (domain.Level, error) {
	ret := _m.Called(levelId)

	if len(ret) == 0 {
		panic("no return value specified for GetLevelById")
	}

	var r0 domain.Level
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.Level, error)); ok {
		return rf(levelId)
	}
	if rf, ok := ret.Get(0).(func(int) domain.Level); ok {
		r0 = rf(levelId)
	} else {
		r0 = ret.Get(0).(domain.Level)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(levelId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLevelList provides a mock function with given fields: fetchStruct
func (_m *Level) GetLevelList(fetchStruct domain.FetchLevelStruct) ([]domain.Level, error) {
	ret := _m.Called(fetchStruct)

	if len(ret) == 0 {
		panic("no return value specified for GetLevelList")
	}

	var r0 []domain.Level
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.FetchLevelStruct) ([]domain.Level, error)); ok {
		return rf(fetchStruct)
	}
	if rf, ok := ret.Get(0).(func(domain.FetchLevelStruct) []domain.Level); ok {
		r0 = rf(fetchStruct)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Level)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.FetchLevelStruct) error); ok {
		r1 = rf(fetchStruct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLevelStats provides a mock function with given fields: levelId
func (_m *Level) GetLevelStats(levelId int) (Statistics.LevelStats, error) {
	ret := _m.Called(levelId)

	if len(ret) == 0 {
		panic("no return value specified for GetLevelStats")
	}

	var r0 Statistics.LevelStats
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (Statistics.LevelStats, error)); ok {
		return rf(levelId)
	}
	if rf, ok := ret.Get(0).(func(int) Statistics.LevelStats); ok {
		r0 = rf(levelId)
	} else {
		r0 = ret.Get(0).(Statistics.LevelStats)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(levelId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLevelUserTop provides a mock function with given fields: levelId
func (_m *Level) GetLevelUserTop(levelId int) ([]Statistics.UserLevelCompletionInfo, error) {
	ret := _m.Called(levelId)

	if len(ret) == 0 {
		panic("no return value specified for GetLevelUserTop")
	}

	var r0 []Statistics.UserLevelCompletionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]Statistics.UserLevelCompletionInfo, error)); ok {
		return rf(levelId)
	}
	if rf, ok := ret.Get(0).(func(int) []Statistics.UserLevelCompletionInfo); ok {
		r0 = rf(levelId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Statistics.UserLevelCompletionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(levelId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLevel provides a mock function with given fields: userId, levelFile, infoFile, previewFile
func (_m *Level) UpdateLevel(userId int, levelFile *multipart.FileHeader, infoFile *multipart.FileHeader, previewFile *multipart.FileHeader) (int, error) {
	ret := _m.Called(userId, levelFile, infoFile, previewFile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLevel")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, *multipart.FileHeader, *multipart.FileHeader, *multipart.FileHeader) (int, error)); ok {
		return rf(userId, levelFile, infoFile, previewFile)
	}
	if rf, ok := ret.Get(0).(func(int, *multipart.FileHeader, *multipart.FileHeader, *multipart.FileHeader) int); ok {
		r0 = rf(userId, levelFile, infoFile, previewFile)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, *multipart.FileHeader, *multipart.FileHeader, *multipart.FileHeader) error); ok {
		r1 = rf(userId, levelFile, infoFile, previewFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLevel creates a new instance of Level. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLevel(t interface {
	mock.TestingT
	Cleanup(func())
}) *Level {
	mock := &Level{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
